variables:
  DOCKER_DRIVER: overlay2
  BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

stages:
  - build

build:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker build --pull -t "$BUILD_IMAGE_NAME" .
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - docker push "$BUILD_IMAGE_NAME"
